// Robograder — Offline archive viewer module
// Loaded dynamically when the user clicks "Export Collection" in Settings.
// Self-contained: no app state required; called with collection data as args.

export { makeSafeBookName, buildArchiveViewer };

// Helper: produce a filesystem-safe folder name from a comic record.
// Lowercase, alphanumeric + underscore only, with title and issue both in the name.
function makeSafeBookName(c) {
  const title = (c.title || 'unknown').toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  const issue = c.issue ? `_${String(c.issue).replace(/[^a-z0-9]/gi, '')}` : '';
  return `${title}${issue}`.slice(0, 80); // cap length
}

// Builds a self-contained HTML archive that can be opened from the unzipped folder.
// The collection data is embedded inline as a JSON literal so no fetch() is needed —
// avoids the file:// CORS restrictions that block sibling-file access in Safari and
// Chrome when the user double-clicks the HTML.
//
// Built as an array of plain strings (not a single template literal) to avoid
// escape-character ambiguity with the nested backticks inside the embedded script.
function buildArchiveViewer(collectionData, exportDate, bookCount) {
  // Embed data via a <script> tag with a JSON literal. Use JSON.stringify with
  // careful escaping — the browser parses this as JS literal, so any <, >, & in
  // the JSON value strings need to be safe. JSON.stringify already handles quotes
  // and backslashes; we just need to break up the closing-script-tag sequence
  // in any defect text (extremely unlikely but defensive).
  const safeJson = JSON.stringify(collectionData).replace(/<\/script/gi, '<\\/script');
  const totalImages = collectionData.reduce((s, c) => s + (c._archiveImageCount || 0), 0);
  const exportDateStr = new Date(exportDate).toLocaleDateString();

  // Built as an array of plain strings (not a single template literal) to avoid
  // escape-character ambiguity with the nested backticks inside the embedded script.
  const lines = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>Robograder Collection Archive</title>',
    '<style>',
    '  body { font-family: -apple-system, "SF Pro Text", "Helvetica Neue", sans-serif; background: #f5f4f2; margin: 0; padding: 20px; color: #1a1614; }',
    '  .header { max-width: 1100px; margin: 0 auto 24px; }',
    '  .header h1 { font-size: 28px; margin: 0 0 4px; }',
    '  .header .meta { font-size: 13px; color: #8a7a6a; }',
    '  .stack { max-width: 1100px; margin: 0 auto; display: flex; flex-direction: column; gap: 18px; }',
    '  .book { background: #ffffff; border: 1px solid #ddd8d0; border-radius: 12px; padding: 18px 20px; }',
    '  .book-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid #eee5d8; }',
    '  .ttl { font-weight: 800; font-size: 20px; line-height: 1.15; color: #1a1614; }',
    '  .iss { font-size: 14px; color: #5a4a3a; margin-top: 3px; }',
    '  .iss-printing { font-size: 13px; color: #8a7a6a; margin-top: 1px; }',
    '  .grades { display: flex; gap: 8px; flex-wrap: wrap; align-items: flex-start; }',
    '  .grade-pip { padding: 6px 10px; border-radius: 8px; font-weight: 700; font-size: 14px; min-width: 56px; text-align: center; line-height: 1.1; }',
    '  .grade-pip.rg { background: #1a3a1e; color: #b8d820; }',
    '  .grade-pip.cgc { background: #1a5fa8; color: #fff; }',
    '  .grade-pip.psa { background: #b91c1c; color: #fff; }',
    '  .grade-pip.cgc-real { background: #fff; border: 1.5px solid #1a5fa8; color: #1a5fa8; }',
    '  .grade-pip.psa-real { background: #fff; border: 1.5px solid #b91c1c; color: #b91c1c; }',
    '  .grade-pip .lbl { display: block; font-size: 9px; opacity: 0.85; letter-spacing: 0.5px; }',
    '  .section { margin-top: 14px; }',
    '  .sect-h { font-size: 11px; font-weight: 700; letter-spacing: 1.2px; text-transform: uppercase; color: #5a4a3a; margin-bottom: 6px; }',
    '  .pq { display: inline-block; padding: 4px 10px; background: #f0e8d4; border-radius: 6px; font-size: 13px; font-weight: 600; color: #5a4830; }',
    '  .rg-components { display: grid; grid-template-columns: repeat(4, 1fr); gap: 6px; max-width: 360px; margin-top: 4px; }',
    '  .rg-comp { background: #f5f0e6; border: 1px solid #e0d8c8; border-radius: 6px; padding: 6px 8px; text-align: center; }',
    '  .rg-comp .n { font-size: 18px; font-weight: 800; color: #1a3a1e; line-height: 1; }',
    '  .rg-comp .l { font-size: 9px; font-weight: 700; letter-spacing: 0.5px; color: #5a6a3a; margin-top: 3px; }',
    '  .narrative { font-size: 13px; line-height: 1.55; color: #2a241e; }',
    '  .notes-list { font-size: 13px; line-height: 1.55; color: #2a241e; margin: 0; padding-left: 16px; }',
    '  .notes-list li { margin-bottom: 2px; }',
    '  .defects { font-size: 13px; line-height: 1.5; color: #2a241e; }',
    '  .defects .d { display: inline-block; margin: 1px 4px 1px 0; padding: 2px 7px; background: #f5f0e6; border-radius: 4px; font-size: 12px; }',
    '  .defects .d.high { background: #fde4e4; color: #8a2020; }',
    '  .defects .d.med { background: #fdefd4; color: #7a5810; }',
    '  .defects .d.low { background: #e8efd4; color: #4a5a20; }',
    '  .costs { display: grid; grid-template-columns: repeat(2, 1fr); gap: 4px 24px; font-size: 13px; max-width: 600px; }',
    '  .costs .row { display: flex; justify-content: space-between; padding: 2px 0; border-bottom: 1px dotted #e8e0cc; }',
    '  .costs .row.total { border-bottom: none; border-top: 1px solid #c8b8a0; margin-top: 4px; padding-top: 4px; font-weight: 700; }',
    '  .costs .lbl { color: #6a5a4a; }',
    '  .costs .val { color: #1a1614; font-variant-numeric: tabular-nums; }',
    '  .imgs { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 10px; margin-top: 6px; }',
    '  .img-tile { position: relative; background: #f0ece2; border-radius: 6px; overflow: hidden; cursor: zoom-in; }',
    '  .img-tile img { width: 100%; height: auto; display: block; }',
    '  .img-tile .cap { position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.6); color: #fff; font-size: 10px; padding: 3px 6px; letter-spacing: 0.5px; text-transform: uppercase; }',
    '  .empty { color: #aaa; font-style: italic; font-size: 12px; }',
    '  /* Lightbox */',
    '  #lightbox { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.92); z-index: 9999; align-items: center; justify-content: center; cursor: zoom-out; padding: 20px; }',
    '  #lightbox.open { display: flex; }',
    '  #lightbox img { max-width: 100%; max-height: 100%; object-fit: contain; }',
    '  #lightbox .close { position: absolute; top: 16px; right: 20px; color: #fff; font-size: 32px; line-height: 1; cursor: pointer; user-select: none; }',
    '</style>',
    '</head>',
    '<body>',
    '  <div class="header">',
    '    <h1>Robograder Collection Archive</h1>',
    '    <div class="meta">' + bookCount + ' books \u00b7 ' + totalImages + ' images \u00b7 exported ' + exportDateStr + '</div>',
    '  </div>',
    '  <div class="stack" id="content"></div>',
    '  <div id="lightbox"><span class="close">\u00d7</span><img id="lightbox-img" alt=""></div>',
    '<' + 'script>',
    '  var BOOKS = ' + safeJson + ';',
    '  function escapeHtml(s) {',
    '    return String(s == null ? "" : s).replace(/[&<>"\\\']/g, function(c){',
    '      return ({"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;","\\\'":"&#39;"})[c];',
    '    });',
    '  }',
    '  function fmtMoney(n) {',
    '    var v = parseFloat(n);',
    '    if (!isFinite(v) || v === 0) return "";',
    '    return "$" + v.toLocaleString("en-US", {minimumFractionDigits: 2, maximumFractionDigits: 2});',
    '  }',
    '  function fmtDate(s) {',
    '    if (!s) return "";',
    '    var d = new Date(s);',
    '    if (isNaN(d.getTime())) return escapeHtml(s);',
    '    return d.toLocaleDateString();',
    '  }',
    '  function buildGrades(b) {',
    '    var rg = b.roboGrade || {};',
    '    var pips = [];',
    '    if (rg.score != null) pips.push(\'<div class="grade-pip rg"><span class="lbl">RG</span>\' + Math.round(rg.score) + \'</div>\');',
    '    if (b.cgcGrade) pips.push(\'<div class="grade-pip cgc-real"><span class="lbl">CGC</span>\' + escapeHtml(b.cgcGrade) + \'</div>\');',
    '    else if (b.assessedCGCGrade) pips.push(\'<div class="grade-pip cgc"><span class="lbl">CGC AI</span>\' + escapeHtml(b.assessedCGCGrade) + \'</div>\');',
    '    if (b.psaGrade) pips.push(\'<div class="grade-pip psa-real"><span class="lbl">PSA</span>\' + escapeHtml(b.psaGrade) + \'</div>\');',
    '    else if (b.assessedPSAGrade) pips.push(\'<div class="grade-pip psa"><span class="lbl">PSA AI</span>\' + escapeHtml(b.assessedPSAGrade) + \'</div>\');',
    '    return pips.join("");',
    '  }',
    '  function buildRgComponents(rg) {',
    '    if (rg.frontScore == null && rg.backScore == null && rg.spineScore == null && rg.interiorScore == null) return "";',
    '    var parts = [',
    '      [rg.frontScore, "FRONT", 50],',
    '      [rg.backScore, "BACK", 20],',
    '      [rg.spineScore, "SPINE", 20],',
    '      [rg.interiorScore, "INTERIOR", 10]',
    '    ];',
    '    var h = \'<div class="rg-components">\';',
    '    parts.forEach(function(p){',
    '      var n = p[0] != null ? Math.round(p[0]) : "\u2014";',
    '      h += \'<div class="rg-comp"><div class="n">\' + n + \'</div><div class="l">\' + p[1] + \' / \' + p[2] + \'</div></div>\';',
    '    });',
    '    h += "</div>";',
    '    return h;',
    '  }',
    '  function buildDefects(rg) {',
    '    if (!rg.defects || !rg.defects.length) return "";',
    '    var grouped = { Front: [], Back: [], Spine: [], Interior: [] };',
    '    rg.defects.forEach(function(d){',
    '      var cat = d.category || "Front";',
    '      if (!grouped[cat]) grouped[cat] = [];',
    '      grouped[cat].push(d);',
    '    });',
    '    var h = \'<div class="defects">\';',
    '    Object.keys(grouped).forEach(function(cat){',
    '      var defs = grouped[cat];',
    '      if (!defs.length) return;',
    '      h += \'<div style="margin-bottom:4px"><strong>\' + cat + \':</strong> \';',
    '      h += defs.map(function(d){',
    '        var sev = (d.severity || "").toLowerCase();',
    '        var cls = sev === "high" ? "d high" : sev === "med" ? "d med" : sev === "low" ? "d low" : "d";',
    '        var txt = escapeHtml(d.type || "defect");',
    '        if (d.location) txt += " (" + escapeHtml(d.location) + ")";',
    '        if (d.measurement) txt += " " + escapeHtml(d.measurement);',
    '        return \'<span class="\' + cls + \'">\' + txt + \'</span>\';',
    '      }).join(" ");',
    '      h += "</div>";',
    '    });',
    '    h += "</div>";',
    '    return h;',
    '  }',
    '  function buildCosts(b) {',
    '    var rows = [',
    '      ["Date acquired", fmtDate(b.dateAcquired)],',
    '      ["Purchase price", fmtMoney(b.purchasePrice)],',
    '      ["Taxes/fees/shipping", fmtMoney(b.taxesFeesShipping)],',
    '      ["Grading cost", fmtMoney(b.gradingCost)],',
    '      ["CGC return shipping", fmtMoney(b.cgcShipping)],',
    '      ["FMV", fmtMoney(b.fmv) + (b.fmvDate ? " (" + fmtDate(b.fmvDate) + ")" : "")]',
    '    ].filter(function(r){ return r[1] && r[1].length; });',
    '    var costFields = [b.purchasePrice, b.taxesFeesShipping, b.gradingCost, b.cgcShipping];',
    '    var total = costFields.reduce(function(s, v){ var n = parseFloat(v); return s + (isFinite(n) ? n : 0); }, 0);',
    '    if (rows.length === 0 && total === 0) return "";',
    '    var h = \'<div class="costs">\';',
    '    rows.forEach(function(r){',
    '      h += \'<div class="row"><span class="lbl">\' + r[0] + \'</span><span class="val">\' + r[1] + \'</span></div>\';',
    '    });',
    '    if (total > 0) {',
    '      h += \'<div class="row total"><span class="lbl">Total cost</span><span class="val">\' + fmtMoney(total) + \'</span></div>\';',
    '    }',
    '    h += "</div>";',
    '    return h;',
    '  }',
    '  function buildImgs(folder, count) {',
    '    var labels = ["front_cover", "back_cover", "page_quality", "raking_light"];',
    '    var captions = ["Front Cover", "Back Cover", "Page Quality", "Raking Light"];',
    '    var h = \'<div class="imgs">\';',
    '    var max = Math.min(count, 4);',
    '    for (var i = 0; i < max; i++) {',
    '      var slot = labels[i] || ("image_" + (i+1));',
    '      var cap = captions[i] || ("Image " + (i+1));',
    '      var src = folder + "/" + slot + ".jpg";',
    '      h += \'<div class="img-tile" data-src="\' + src + \'">\';',
    '      h += \'<img src="\' + src + \'" alt="\' + cap + \'" onerror="this.parentElement.dataset.src=this.src=\\\'\' + folder + \'/\' + slot + \'.png\\\';this.onerror=null">\';',
    '      h += \'<div class="cap">\' + cap + \'</div>\';',
    '      h += "</div>";',
    '    }',
    '    h += "</div>";',
    '    return h;',
    '  }',
    '  function section(title, body) {',
    '    if (!body) return "";',
    '    return \'<div class="section"><div class="sect-h">\' + title + \'</div>\' + body + \'</div>\';',
    '  }',
    '  function buildNotesList(notes) {',
    '    if (!notes) return "";',
    '    var lines = String(notes).split(/\\n+/).map(function(s){ return s.trim(); }).filter(Boolean);',
    '    if (!lines.length) return "";',
    '    if (lines.length === 1) return \'<div class="narrative">\' + escapeHtml(lines[0]) + \'</div>\';',
    '    return \'<ul class="notes-list">\' + lines.map(function(l){',
    '      var clean = l.replace(/^[\\u2022\\-\\*]\\s*/, "");',
    '      return "<li>" + escapeHtml(clean) + "</li>";',
    '    }).join("") + "</ul>";',
    '  }',
    '  var content = document.getElementById("content");',
    '  BOOKS.forEach(function(b){',
    '    var div = document.createElement("div");',
    '    div.className = "book";',
    '    var rg = b.roboGrade || {};',
    '    var html = "";',
    '    // Header: title/issue on left, grades on right',
    '    html += \'<div class="book-head">\';',
    '    html += \'<div>\';',
    '    html += \'<div class="ttl">\' + escapeHtml(b.title || "Untitled") + \'</div>\';',
    '    html += \'<div class="iss">#\' + escapeHtml(b.issue || "?") + (b.issueDate ? " \u00b7 " + escapeHtml(b.issueDate) : "") + \'</div>\';',
    '    if (b.printing) html += \'<div class="iss-printing">\' + escapeHtml(b.printing) + \'</div>\';',
    '    html += \'</div>\';',
    '    html += \'<div class="grades">\' + buildGrades(b) + \'</div>\';',
    '    html += \'</div>\';',
    '    // Page quality',
    '    if (b.pageQuality) {',
    '      html += section("Page Quality", \'<span class="pq">\' + escapeHtml(b.pageQuality) + \'</span>\');',
    '    }',
    '    // RG components',
    '    if (rg.score != null) {',
    '      html += section("Robograde Component Scores", buildRgComponents(rg));',
    '    }',
    '    // RG defects',
    '    html += section("Robograde Defects", buildDefects(rg));',
    '    // RG narrative (assessmentNotes from RG OR aiAssessment)',
    '    var rgNarrative = rg.assessmentNotes || b.aiAssessment;',
    '    if (rgNarrative) html += section("Assessment Notes", \'<div class="narrative">\' + escapeHtml(rgNarrative) + \'</div>\');',
    '    // RG notes (graderNotes / aiGraderNotes — bullet-style defect list)',
    '    if (b.aiGraderNotes) html += section("RG Grader Notes", buildNotesList(b.aiGraderNotes));',
    '    if (b.graderNotes) html += section("Official Grader Notes", buildNotesList(b.graderNotes));',
    '    if (b.cgcNotes) html += section("CGC Label Notes", buildNotesList(b.cgcNotes));',
    '    if (b.psaNotes) html += section("PSA Label Notes", buildNotesList(b.psaNotes));',
    '    // Personal notes',
    '    if (b.notes) html += section("Personal Notes", \'<div class="narrative">\' + escapeHtml(b.notes) + \'</div>\');',
    '    // Costs',
    '    var costsHtml = buildCosts(b);',
    '    if (costsHtml) html += section("Acquisition & Costs", costsHtml);',
    '    // Images',
    '    if (b._archiveFolder && b._archiveImageCount) {',
    '      html += section("Photos", buildImgs(b._archiveFolder, b._archiveImageCount));',
    '    }',
    '    div.innerHTML = html;',
    '    content.appendChild(div);',
    '  });',
    '  // Lightbox: click any image tile to view full-size; click background or X to close',
    '  var lb = document.getElementById("lightbox");',
    '  var lbImg = document.getElementById("lightbox-img");',
    '  document.addEventListener("click", function(e){',
    '    var tile = e.target.closest && e.target.closest(".img-tile");',
    '    if (tile && tile.dataset.src) {',
    '      lbImg.src = tile.dataset.src;',
    '      lb.classList.add("open");',
    '      return;',
    '    }',
    '    if (e.target.id === "lightbox" || e.target.classList.contains("close") || e.target === lbImg) {',
    '      lb.classList.remove("open");',
    '      lbImg.src = "";',
    '    }',
    '  });',
    '  document.addEventListener("keydown", function(e){',
    '    if (e.key === "Escape" && lb.classList.contains("open")) {',
    '      lb.classList.remove("open");',
    '      lbImg.src = "";',
    '    }',
    '  });',
    '<' + '/script>',
    '</body>',
    '</html>'
  ];
  return lines.join('\n');
}
